<?php

include'config.php';




$sqlval1 = "SELECT * FROM firstyear WHERE id='$studentid'";
$resultval1 = mysqli_query($conn, $sqlval1);

if (mysqli_num_rows($resultval1) > 0)
{
    // output data of each row
   
     while($arrayval1=mysqli_fetch_row($resultval1)) 
    {
        for($i=0;$i<=176;$i++)
        {
          $subval1[]=$arrayval1[$i];
            
        }
         
    }
}
else {
//    echo "Error: " . $sqlval . "<br>" . mysqli_error($conn);
}


echo "<script type=\"text/javascript\">
document.getElementById('arr1').innerHTML ='$subval1[1]'
document.getElementById('arr2').innerHTML ='$subval1[2]'
document.getElementById('arr3').innerHTML ='$subval1[3]'
document.getElementById('arr4').innerHTML ='$subval1[4]'
document.getElementById('arr5').innerHTML ='$subval1[5]'
document.getElementById('arr6').innerHTML ='$subval1[6]'
document.getElementById('arr7').innerHTML ='$subval1[7]'
document.getElementById('arr8').innerHTML ='$subval1[8]'
document.getElementById('arr9').innerHTML ='$subval1[9]'
document.getElementById('arr10').innerHTML ='$subval1[10]'
document.getElementById('arr11').innerHTML ='$subval1[11]'
document.getElementById('arr12').innerHTML ='$subval1[12]'
document.getElementById('arr13').innerHTML ='$subval1[13]'
document.getElementById('arr14').innerHTML ='$subval1[14]'
document.getElementById('arr15').innerHTML ='$subval1[15]'
document.getElementById('arr16').innerHTML ='$subval1[16]'
document.getElementById('arr17').innerHTML ='$subval1[17]'
document.getElementById('arr18').innerHTML ='$subval1[18]'
document.getElementById('arr19').innerHTML ='$subval1[19]'
document.getElementById('arr20').innerHTML ='$subval1[20]'
document.getElementById('arr21').innerHTML ='$subval1[21]'
document.getElementById('arr22').innerHTML ='$subval1[22]'
document.getElementById('arr23').innerHTML ='$subval1[23]'
document.getElementById('arr24').innerHTML ='$subval1[24]'
document.getElementById('arr25').innerHTML ='$subval1[25]'
document.getElementById('arr26').innerHTML ='$subval1[26]'
document.getElementById('arr27').innerHTML ='$subval1[27]'
document.getElementById('arr28').innerHTML ='$subval1[28]'
document.getElementById('arr29').innerHTML ='$subval1[29]'
document.getElementById('arr30').innerHTML ='$subval1[30]'
document.getElementById('arr31').innerHTML ='$subval1[31]'
document.getElementById('arr32').innerHTML ='$subval1[32]'
document.getElementById('arr33').innerHTML ='$subval1[33]'
document.getElementById('arr34').innerHTML ='$subval1[34]'
document.getElementById('arr35').innerHTML ='$subval1[35]'
document.getElementById('arr36').innerHTML ='$subval1[36]'
document.getElementById('arr37').innerHTML ='$subval1[37]'
document.getElementById('arr38').innerHTML ='$subval1[38]'
document.getElementById('arr39').innerHTML ='$subval1[39]'
document.getElementById('arr40').innerHTML ='$subval1[40]'
document.getElementById('arr41').innerHTML ='$subval1[41]'
document.getElementById('arr42').innerHTML ='$subval1[42]'
document.getElementById('arr43').innerHTML ='$subval1[43]'
document.getElementById('arr44').innerHTML ='$subval1[44]'
document.getElementById('arr46').innerHTML ='$subval1[46]'
document.getElementById('arr48').innerHTML ='$subval1[48]'
document.getElementById('arr49').innerHTML ='$subval1[49]'
document.getElementById('arr51').innerHTML ='$subval1[51]'
document.getElementById('arr53').innerHTML ='$subval1[53]'
document.getElementById('arr54').innerHTML ='$subval1[54]'
document.getElementById('arr55').innerHTML ='$subval1[55]'
document.getElementById('arr57').innerHTML ='$subval1[57]'
document.getElementById('arr59').innerHTML ='$subval1[59]'
document.getElementById('arr60').innerHTML ='$subval1[60]'
document.getElementById('arr62').innerHTML ='$subval1[62]'
document.getElementById('arr64').innerHTML ='$subval1[64]'
document.getElementById('arr65').innerHTML ='$subval1[65]'
document.getElementById('arr66').innerHTML ='$subval1[66]'
document.getElementById('arr67').innerHTML ='$subval1[67]'
document.getElementById('arr68').innerHTML ='$subval1[68]'
document.getElementById('arr69').innerHTML ='$subval1[69]'
document.getElementById('arr70').innerHTML ='$subval1[70]'
document.getElementById('arr71').innerHTML ='$subval1[71]'
document.getElementById('arr72').innerHTML ='$subval1[72]'
document.getElementById('arr73').innerHTML ='$subval1[73]'
document.getElementById('arr74').innerHTML ='$subval1[74]'
document.getElementById('arr75').innerHTML ='$subval1[75]'
document.getElementById('arr76').innerHTML ='$subval1[76]'
document.getElementById('arr77').innerHTML ='$subval1[77]'
document.getElementById('arr78').innerHTML ='$subval1[78]'
document.getElementById('arr79').innerHTML ='$subval1[79]'
document.getElementById('arr80').innerHTML ='$subval1[80]'
document.getElementById('arr81').innerHTML ='$subval1[81]'
document.getElementById('arr82').innerHTML ='$subval1[82]'
document.getElementById('arr83').innerHTML ='$subval1[83]'
document.getElementById('arr84').innerHTML ='$subval1[84]'
document.getElementById('arr85').innerHTML ='$subval1[85]'
document.getElementById('arr86').innerHTML ='$subval1[86]'
document.getElementById('arr87').innerHTML ='$subval1[87]'
document.getElementById('arr88').innerHTML ='$subval1[88]'
document.getElementById('arr89').innerHTML ='$subval1[89]'
document.getElementById('arr90').innerHTML ='$subval1[90]'
document.getElementById('arr91').innerHTML ='$subval1[91]'
document.getElementById('arr92').innerHTML ='$subval1[92]'
document.getElementById('arr93').innerHTML ='$subval1[93]'
document.getElementById('arr94').innerHTML ='$subval1[94]'
document.getElementById('arr95').innerHTML ='$subval1[95]'
document.getElementById('arr96').innerHTML ='$subval1[96]'
document.getElementById('arr97').innerHTML ='$subval1[97]'
document.getElementById('arr98').innerHTML ='$subval1[98]'
document.getElementById('arr99').innerHTML ='$subval1[99]'
document.getElementById('arr100').innerHTML ='$subval1[100]'
document.getElementById('arr101').innerHTML ='$subval1[101]'
document.getElementById('arr102').innerHTML ='$subval1[102]'
document.getElementById('arr103').innerHTML ='$subval1[103]'
document.getElementById('arr104').innerHTML ='$subval1[104]'
document.getElementById('arr105').innerHTML ='$subval1[105]'
document.getElementById('arr106').innerHTML ='$subval1[106]'
document.getElementById('arr107').innerHTML ='$subval1[107]'
document.getElementById('arr108').innerHTML ='$subval1[108]'
document.getElementById('arr109').innerHTML ='$subval1[109]'
document.getElementById('arr110').innerHTML ='$subval1[110]'
document.getElementById('arr112').innerHTML ='$subval1[112]'
document.getElementById('arr114').innerHTML ='$subval1[114]'
document.getElementById('arr115').innerHTML ='$subval1[115]'
document.getElementById('arr117').innerHTML ='$subval1[117]'
document.getElementById('arr119').innerHTML ='$subval1[119]'
document.getElementById('arr120').innerHTML ='$subval1[120]'
document.getElementById('arr121').innerHTML ='$subval1[121]'
document.getElementById('arr123').innerHTML ='$subval1[123]'
document.getElementById('arr125').innerHTML ='$subval1[125]'
document.getElementById('arr126').innerHTML ='$subval1[126]'
document.getElementById('arr128').innerHTML ='$subval1[128]'
document.getElementById('arr130').innerHTML ='$subval1[130]'
document.getElementById('arr131').innerHTML ='$subval1[131]'
document.getElementById('arr132').innerHTML ='$subval1[132]'
document.getElementById('arr133').innerHTML ='$subval1[133]'
document.getElementById('arr134').innerHTML ='$subval1[134]'
document.getElementById('arr135').innerHTML ='$subval1[135]'
document.getElementById('arr136').innerHTML ='$subval1[136]'
document.getElementById('arr137').innerHTML ='$subval1[137]'
document.getElementById('arr138').innerHTML ='$subval1[138]'
document.getElementById('arr139').innerHTML ='$subval1[139]'
document.getElementById('arr140').innerHTML ='$subval1[140]'
document.getElementById('arr141').innerHTML ='$subval1[141]'
document.getElementById('arr142').innerHTML ='$subval1[142]'
document.getElementById('arr143').innerHTML ='$subval1[143]'
document.getElementById('arr144').innerHTML ='$subval1[144]'
document.getElementById('arr145').innerHTML ='$subval1[145]'
document.getElementById('arr146').innerHTML ='$subval1[146]'
document.getElementById('arr147').innerHTML ='$subval1[147]'
document.getElementById('arr148').innerHTML ='$subval1[148]'
document.getElementById('arr149').innerHTML ='$subval1[149]'
document.getElementById('arr150').innerHTML ='$subval1[150]'
document.getElementById('arr151').innerHTML ='$subval1[151]'
document.getElementById('arr152').innerHTML ='$subval1[152]'
document.getElementById('arr153').innerHTML ='$subval1[153]'
document.getElementById('arr154').innerHTML ='$subval1[154]'
document.getElementById('arr155').innerHTML ='$subval1[155]'
document.getElementById('arr156').innerHTML ='$subval1[156]'
document.getElementById('arr157').innerHTML ='$subval1[157]'
document.getElementById('arr158').innerHTML ='$subval1[158]'
document.getElementById('arr159').innerHTML ='$subval1[159]'
document.getElementById('arr160').innerHTML ='$subval1[160]'
document.getElementById('arr161').innerHTML ='$subval1[161]'
document.getElementById('arr162').innerHTML ='$subval1[162]'
document.getElementById('arr163').innerHTML ='$subval1[163]'
document.getElementById('arr164').innerHTML ='$subval1[164]'
document.getElementById('arr165').innerHTML ='$subval1[165]'
document.getElementById('arr166').innerHTML ='$subval1[166]'
document.getElementById('arr167').innerHTML ='$subval1[167]'
document.getElementById('arr168').innerHTML ='$subval1[168]'
document.getElementById('arr169').innerHTML ='$subval1[169]'
document.getElementById('arr170').innerHTML ='$subval1[170]'
document.getElementById('arr171').innerHTML ='$subval1[171]'
document.getElementById('arr172').innerHTML ='$subval1[172]'
document.getElementById('arr173').innerHTML ='$subval1[173]'
document.getElementById('arr174').innerHTML ='$subval1[174]'
document.getElementById('arr175').innerHTML ='$subval1[175]'
document.getElementById('arr176').innerHTML ='$subval1[176]'
 
    </script>";
  


//First Year Printing Ended Here //////



/////Second Year Printing Starts here///// 



$sqlval2 = "SELECT * FROM secondyear WHERE id='$studentid'";
$resultval2 = mysqli_query($conn, $sqlval2);

if (mysqli_num_rows($resultval2) > 0){
    // output data of each row
   
     while($arrayval2=mysqli_fetch_row($resultval2)) 
    {
        for($i=0;$i<=176;$i++)
        {
          $subval2[]=$arrayval2[$i];
            
        }
         
    }
}
else {
//    echo "Error: " . $sqlval2 . "<br>" . mysqli_error($conn);
}
echo "<script type=\"text/javascript\">

document.getElementById('arr201').innerHTML ='$subval2[1]'
document.getElementById('arr202').innerHTML ='$subval2[2]'
document.getElementById('arr203').innerHTML ='$subval2[3]'
document.getElementById('arr204').innerHTML ='$subval2[4]'
document.getElementById('arr205').innerHTML ='$subval2[5]'
document.getElementById('arr206').innerHTML ='$subval2[6]'
document.getElementById('arr207').innerHTML ='$subval2[7]'
document.getElementById('arr208').innerHTML ='$subval2[8]'
document.getElementById('arr209').innerHTML ='$subval2[9]'
document.getElementById('arr210').innerHTML ='$subval2[10]'
document.getElementById('arr211').innerHTML ='$subval2[11]'
document.getElementById('arr212').innerHTML ='$subval2[12]'
document.getElementById('arr213').innerHTML ='$subval2[13]'
document.getElementById('arr214').innerHTML ='$subval2[14]'
document.getElementById('arr215').innerHTML ='$subval2[15]'
document.getElementById('arr216').innerHTML ='$subval2[16]'
document.getElementById('arr217').innerHTML ='$subval2[17]'
document.getElementById('arr218').innerHTML ='$subval2[18]'
document.getElementById('arr219').innerHTML ='$subval2[19]'
document.getElementById('arr220').innerHTML ='$subval2[20]'
document.getElementById('arr221').innerHTML ='$subval2[21]'
document.getElementById('arr222').innerHTML ='$subval2[22]'
document.getElementById('arr223').innerHTML ='$subval2[23]'
document.getElementById('arr224').innerHTML ='$subval2[24]'
document.getElementById('arr225').innerHTML ='$subval2[25]'
document.getElementById('arr226').innerHTML ='$subval2[26]'
document.getElementById('arr227').innerHTML ='$subval2[27]'
document.getElementById('arr228').innerHTML ='$subval2[28]'
document.getElementById('arr229').innerHTML ='$subval2[29]'
document.getElementById('arr230').innerHTML ='$subval2[30]'
document.getElementById('arr231').innerHTML ='$subval2[31]'
document.getElementById('arr232').innerHTML ='$subval2[32]'
document.getElementById('arr233').innerHTML ='$subval2[33]'
document.getElementById('arr234').innerHTML ='$subval2[34]'
document.getElementById('arr235').innerHTML ='$subval2[35]'
document.getElementById('arr236').innerHTML ='$subval2[36]'
document.getElementById('arr237').innerHTML ='$subval2[37]'
document.getElementById('arr238').innerHTML ='$subval2[38]'
document.getElementById('arr239').innerHTML ='$subval2[39]'
document.getElementById('arr240').innerHTML ='$subval2[40]'
document.getElementById('arr241').innerHTML ='$subval2[41]'
document.getElementById('arr242').innerHTML ='$subval2[42]'
document.getElementById('arr243').innerHTML ='$subval2[43]'
document.getElementById('arr244').innerHTML ='$subval2[44]'
document.getElementById('arr246').innerHTML ='$subval2[46]'
document.getElementById('arr248').innerHTML ='$subval2[48]'
document.getElementById('arr249').innerHTML ='$subval2[49]'
document.getElementById('arr251').innerHTML ='$subval2[51]'
document.getElementById('arr253').innerHTML ='$subval2[53]'
document.getElementById('arr254').innerHTML ='$subval2[54]'
document.getElementById('arr255').innerHTML ='$subval2[55]'
document.getElementById('arr257').innerHTML ='$subval2[57]'
document.getElementById('arr259').innerHTML ='$subval2[59]'
document.getElementById('arr260').innerHTML ='$subval2[60]'
document.getElementById('arr262').innerHTML ='$subval2[62]'
document.getElementById('arr264').innerHTML ='$subval2[64]'
document.getElementById('arr265').innerHTML ='$subval2[65]'
document.getElementById('arr266').innerHTML ='$subval2[66]'
document.getElementById('arr267').innerHTML ='$subval2[67]'
document.getElementById('arr268').innerHTML ='$subval2[68]'
document.getElementById('arr269').innerHTML ='$subval2[69]'
document.getElementById('arr270').innerHTML ='$subval2[70]'
document.getElementById('arr271').innerHTML ='$subval2[71]'
document.getElementById('arr272').innerHTML ='$subval2[72]'
document.getElementById('arr273').innerHTML ='$subval2[73]'
document.getElementById('arr274').innerHTML ='$subval2[74]'
document.getElementById('arr275').innerHTML ='$subval2[75]'
document.getElementById('arr276').innerHTML ='$subval2[76]'
document.getElementById('arr277').innerHTML ='$subval2[77]'
document.getElementById('arr278').innerHTML ='$subval2[78]'
document.getElementById('arr279').innerHTML ='$subval2[79]'
document.getElementById('arr280').innerHTML ='$subval2[80]'
document.getElementById('arr281').innerHTML ='$subval2[81]'
document.getElementById('arr282').innerHTML ='$subval2[82]'
document.getElementById('arr283').innerHTML ='$subval2[83]'
document.getElementById('arr284').innerHTML ='$subval2[84]'
document.getElementById('arr285').innerHTML ='$subval2[85]'
document.getElementById('arr286').innerHTML ='$subval2[86]'
document.getElementById('arr287').innerHTML ='$subval2[87]'
document.getElementById('arr288').innerHTML ='$subval2[88]'
document.getElementById('arr289').innerHTML ='$subval2[89]'
document.getElementById('arr290').innerHTML ='$subval2[90]'
document.getElementById('arr291').innerHTML ='$subval2[91]'
document.getElementById('arr292').innerHTML ='$subval2[92]'
document.getElementById('arr293').innerHTML ='$subval2[93]'
document.getElementById('arr294').innerHTML ='$subval2[94]'
document.getElementById('arr295').innerHTML ='$subval2[95]'
document.getElementById('arr296').innerHTML ='$subval2[96]'
document.getElementById('arr297').innerHTML ='$subval2[97]'
document.getElementById('arr298').innerHTML ='$subval2[98]'
document.getElementById('arr299').innerHTML ='$subval2[99]'
document.getElementById('arr300').innerHTML ='$subval2[100]'
document.getElementById('arr301').innerHTML ='$subval2[101]'
document.getElementById('arr302').innerHTML ='$subval2[102]'
document.getElementById('arr303').innerHTML ='$subval2[103]'
document.getElementById('arr304').innerHTML ='$subval2[104]'
document.getElementById('arr305').innerHTML ='$subval2[105]'
document.getElementById('arr306').innerHTML ='$subval2[106]'
document.getElementById('arr307').innerHTML ='$subval2[107]'
document.getElementById('arr308').innerHTML ='$subval2[108]'
document.getElementById('arr309').innerHTML ='$subval2[109]'
document.getElementById('arr310').innerHTML ='$subval2[110]'
document.getElementById('arr312').innerHTML ='$subval2[112]'
document.getElementById('arr314').innerHTML ='$subval2[114]'
document.getElementById('arr315').innerHTML ='$subval2[115]'
document.getElementById('arr317').innerHTML ='$subval2[117]'
document.getElementById('arr319').innerHTML ='$subval2[119]'
document.getElementById('arr320').innerHTML ='$subval2[120]'
document.getElementById('arr321').innerHTML ='$subval2[121]'
document.getElementById('arr323').innerHTML ='$subval2[123]'
document.getElementById('arr325').innerHTML ='$subval2[125]'
document.getElementById('arr326').innerHTML ='$subval2[126]'
document.getElementById('arr328').innerHTML ='$subval2[128]'
document.getElementById('arr330').innerHTML ='$subval2[130]'
document.getElementById('arr331').innerHTML ='$subval2[131]'
document.getElementById('arr332').innerHTML ='$subval2[132]'
document.getElementById('arr333').innerHTML ='$subval2[133]'
document.getElementById('arr334').innerHTML ='$subval2[134]'
document.getElementById('arr335').innerHTML ='$subval2[135]'
document.getElementById('arr336').innerHTML ='$subval2[136]'
document.getElementById('arr337').innerHTML ='$subval2[137]'
document.getElementById('arr338').innerHTML ='$subval2[138]'
document.getElementById('arr339').innerHTML ='$subval2[139]'
document.getElementById('arr340').innerHTML ='$subval2[140]'
document.getElementById('arr341').innerHTML ='$subval2[141]'
document.getElementById('arr342').innerHTML ='$subval2[142]'
document.getElementById('arr343').innerHTML ='$subval2[143]'
document.getElementById('arr344').innerHTML ='$subval2[144]'
document.getElementById('arr345').innerHTML ='$subval2[145]'
document.getElementById('arr346').innerHTML ='$subval2[146]'
document.getElementById('arr347').innerHTML ='$subval2[147]'
document.getElementById('arr348').innerHTML ='$subval2[148]'
document.getElementById('arr349').innerHTML ='$subval2[149]'
document.getElementById('arr350').innerHTML ='$subval2[150]'
document.getElementById('arr351').innerHTML ='$subval2[151]'
document.getElementById('arr352').innerHTML ='$subval2[152]'
document.getElementById('arr353').innerHTML ='$subval2[153]'
document.getElementById('arr354').innerHTML ='$subval2[154]'
document.getElementById('arr355').innerHTML ='$subval2[155]'
document.getElementById('arr356').innerHTML ='$subval2[156]'
document.getElementById('arr357').innerHTML ='$subval2[157]'
document.getElementById('arr358').innerHTML ='$subval2[158]'
document.getElementById('arr359').innerHTML ='$subval2[159]'
document.getElementById('arr360').innerHTML ='$subval2[160]'
document.getElementById('arr361').innerHTML ='$subval2[161]'
document.getElementById('arr362').innerHTML ='$subval2[162]'
document.getElementById('arr363').innerHTML ='$subval2[163]'
document.getElementById('arr364').innerHTML ='$subval2[164]'
document.getElementById('arr365').innerHTML ='$subval2[165]'
document.getElementById('arr366').innerHTML ='$subval2[166]'
document.getElementById('arr367').innerHTML ='$subval2[167]'
document.getElementById('arr368').innerHTML ='$subval2[168]'
document.getElementById('arr369').innerHTML ='$subval2[169]'
document.getElementById('arr370').innerHTML ='$subval2[170]'
document.getElementById('arr371').innerHTML ='$subval2[171]'
document.getElementById('arr372').innerHTML ='$subval2[172]'
   
    </script>";


/////Secon year Printing starts Here////////




///Third year Printing starts Here////

$sqlval3 = "SELECT * FROM thirdyear WHERE id='$studentid'";
$resultval3= mysqli_query($conn, $sqlval3);

if (mysqli_num_rows($resultval3) > 0){
    // output data of each row
   
     while($arrayval3=mysqli_fetch_row($resultval3)) 
    {
        for($i=0;$i<=176;$i++)
        {
          $subval3[]=$arrayval3[$i];
            
        }
         
    }
}
else {
//    echo "Error: " . $sqlval . "<br>" . mysqli_error($conn);
}
echo "<script type=\"text/javascript\">

document.getElementById('arr401').innerHTML ='$subval3[1]'
document.getElementById('arr402').innerHTML ='$subval3[2]'
document.getElementById('arr403').innerHTML ='$subval3[3]'
document.getElementById('arr404').innerHTML ='$subval3[4]'
document.getElementById('arr405').innerHTML ='$subval3[5]'
document.getElementById('arr406').innerHTML ='$subval3[6]'
document.getElementById('arr407').innerHTML ='$subval3[7]'
document.getElementById('arr408').innerHTML ='$subval3[8]'
document.getElementById('arr409').innerHTML ='$subval3[9]'
document.getElementById('arr410').innerHTML ='$subval3[10]'
document.getElementById('arr411').innerHTML ='$subval3[11]'
document.getElementById('arr412').innerHTML ='$subval3[12]'
document.getElementById('arr413').innerHTML ='$subval3[13]'
document.getElementById('arr414').innerHTML ='$subval3[14]'
document.getElementById('arr415').innerHTML ='$subval3[15]'
document.getElementById('arr416').innerHTML ='$subval3[16]'
document.getElementById('arr417').innerHTML ='$subval3[17]'
document.getElementById('arr418').innerHTML ='$subval3[18]'
document.getElementById('arr419').innerHTML ='$subval3[19]'
document.getElementById('arr420').innerHTML ='$subval3[20]'
document.getElementById('arr421').innerHTML ='$subval3[21]'
document.getElementById('arr422').innerHTML ='$subval3[22]'
document.getElementById('arr423').innerHTML ='$subval3[23]'
document.getElementById('arr424').innerHTML ='$subval3[24]'
document.getElementById('arr425').innerHTML ='$subval3[25]'
document.getElementById('arr426').innerHTML ='$subval3[26]'
document.getElementById('arr427').innerHTML ='$subval3[27]'
document.getElementById('arr428').innerHTML ='$subval3[28]'
document.getElementById('arr429').innerHTML ='$subval3[29]'
document.getElementById('arr430').innerHTML ='$subval3[30]'
document.getElementById('arr431').innerHTML ='$subval3[31]'
document.getElementById('arr432').innerHTML ='$subval3[32]'
document.getElementById('arr433').innerHTML ='$subval3[33]'
document.getElementById('arr434').innerHTML ='$subval3[34]'
document.getElementById('arr435').innerHTML ='$subval3[35]'
document.getElementById('arr436').innerHTML ='$subval3[36]'
document.getElementById('arr437').innerHTML ='$subval3[37]'
document.getElementById('arr438').innerHTML ='$subval3[38]'
document.getElementById('arr439').innerHTML ='$subval3[39]'
document.getElementById('arr440').innerHTML ='$subval3[40]'
document.getElementById('arr441').innerHTML ='$subval3[41]'
document.getElementById('arr442').innerHTML ='$subval3[42]'
document.getElementById('arr443').innerHTML ='$subval3[43]'
document.getElementById('arr444').innerHTML ='$subval3[44]'
document.getElementById('arr446').innerHTML ='$subval3[46]'
document.getElementById('arr448').innerHTML ='$subval3[48]'
document.getElementById('arr449').innerHTML ='$subval3[49]'
document.getElementById('arr451').innerHTML ='$subval3[51]'
document.getElementById('arr453').innerHTML ='$subval3[53]'
document.getElementById('arr454').innerHTML ='$subval3[54]'
document.getElementById('arr455').innerHTML ='$subval3[55]'
document.getElementById('arr457').innerHTML ='$subval3[57]'
document.getElementById('arr459').innerHTML ='$subval3[59]'
document.getElementById('arr460').innerHTML ='$subval3[60]'
document.getElementById('arr462').innerHTML ='$subval3[62]'
document.getElementById('arr464').innerHTML ='$subval3[64]'
document.getElementById('arr465').innerHTML ='$subval3[65]'
document.getElementById('arr466').innerHTML ='$subval3[66]'
document.getElementById('arr467').innerHTML ='$subval3[67]'
document.getElementById('arr468').innerHTML ='$subval3[68]'
document.getElementById('arr469').innerHTML ='$subval3[69]'
document.getElementById('arr470').innerHTML ='$subval3[70]'
document.getElementById('arr471').innerHTML ='$subval3[71]'
document.getElementById('arr472').innerHTML ='$subval3[72]'
document.getElementById('arr473').innerHTML ='$subval3[73]'
document.getElementById('arr474').innerHTML ='$subval3[74]'
document.getElementById('arr475').innerHTML ='$subval3[75]'
document.getElementById('arr476').innerHTML ='$subval3[76]'
document.getElementById('arr477').innerHTML ='$subval3[77]'
document.getElementById('arr478').innerHTML ='$subval3[78]'
document.getElementById('arr479').innerHTML ='$subval3[79]'
document.getElementById('arr480').innerHTML ='$subval3[80]'
document.getElementById('arr481').innerHTML ='$subval3[81]'
document.getElementById('arr482').innerHTML ='$subval3[82]'
document.getElementById('arr483').innerHTML ='$subval3[83]'
document.getElementById('arr484').innerHTML ='$subval3[84]'
document.getElementById('arr485').innerHTML ='$subval3[85]'
document.getElementById('arr486').innerHTML ='$subval3[86]'
document.getElementById('arr487').innerHTML ='$subval3[87]'
document.getElementById('arr488').innerHTML ='$subval3[88]'
document.getElementById('arr489').innerHTML ='$subval3[89]'
document.getElementById('arr490').innerHTML ='$subval3[90]'
document.getElementById('arr491').innerHTML ='$subval3[91]'
document.getElementById('arr492').innerHTML ='$subval3[92]'
document.getElementById('arr493').innerHTML ='$subval3[93]'
document.getElementById('arr494').innerHTML ='$subval3[94]'
document.getElementById('arr495').innerHTML ='$subval3[95]'
document.getElementById('arr496').innerHTML ='$subval3[96]'
document.getElementById('arr497').innerHTML ='$subval3[97]'
document.getElementById('arr498').innerHTML ='$subval3[98]'
document.getElementById('arr499').innerHTML ='$subval3[99]'
document.getElementById('arr500').innerHTML ='$subval3[100]'
document.getElementById('arr501').innerHTML ='$subval3[101]'
document.getElementById('arr502').innerHTML ='$subval3[102]'
document.getElementById('arr503').innerHTML ='$subval3[103]'
document.getElementById('arr504').innerHTML ='$subval3[104]'
document.getElementById('arr505').innerHTML ='$subval3[105]'
document.getElementById('arr506').innerHTML ='$subval3[106]'
document.getElementById('arr507').innerHTML ='$subval3[107]'
document.getElementById('arr508').innerHTML ='$subval3[108]'
document.getElementById('arr509').innerHTML ='$subval3[109]'
document.getElementById('arr510').innerHTML ='$subval3[110]'
document.getElementById('arr512').innerHTML ='$subval3[112]'
document.getElementById('arr514').innerHTML ='$subval3[114]'
document.getElementById('arr515').innerHTML ='$subval3[115]'
document.getElementById('arr517').innerHTML ='$subval3[117]'
document.getElementById('arr519').innerHTML ='$subval3[119]'
document.getElementById('arr520').innerHTML ='$subval3[120]'
document.getElementById('arr521').innerHTML ='$subval3[121]'
document.getElementById('arr523').innerHTML ='$subval3[123]'
document.getElementById('arr525').innerHTML ='$subval3[125]'
document.getElementById('arr526').innerHTML ='$subval3[126]'
document.getElementById('arr528').innerHTML ='$subval3[128]'
document.getElementById('arr530').innerHTML ='$subval3[130]'
document.getElementById('arr531').innerHTML ='$subval3[131]'
document.getElementById('arr532').innerHTML ='$subval3[132]'
document.getElementById('arr533').innerHTML ='$subval3[133]'
document.getElementById('arr534').innerHTML ='$subval3[134]'
document.getElementById('arr535').innerHTML ='$subval3[135]'
document.getElementById('arr536').innerHTML ='$subval3[136]'
document.getElementById('arr537').innerHTML ='$subval3[137]'
document.getElementById('arr538').innerHTML ='$subval3[138]'
document.getElementById('arr539').innerHTML ='$subval3[139]'
document.getElementById('arr540').innerHTML ='$subval3[140]'
document.getElementById('arr541').innerHTML ='$subval3[141]'
document.getElementById('arr542').innerHTML ='$subval3[142]'
document.getElementById('arr543').innerHTML ='$subval3[143]'
document.getElementById('arr544').innerHTML ='$subval3[144]'
document.getElementById('arr545').innerHTML ='$subval3[145]'
document.getElementById('arr546').innerHTML ='$subval3[146]'
document.getElementById('arr547').innerHTML ='$subval3[147]'
document.getElementById('arr548').innerHTML ='$subval3[148]'
document.getElementById('arr549').innerHTML ='$subval3[149]'
document.getElementById('arr550').innerHTML ='$subval3[150]'
document.getElementById('arr551').innerHTML ='$subval3[151]'
document.getElementById('arr552').innerHTML ='$subval3[152]'
document.getElementById('arr553').innerHTML ='$subval3[153]'
document.getElementById('arr554').innerHTML ='$subval3[154]'
document.getElementById('arr555').innerHTML ='$subval3[155]'
document.getElementById('arr556').innerHTML ='$subval3[156]'
document.getElementById('arr557').innerHTML ='$subval3[157]'
document.getElementById('arr558').innerHTML ='$subval3[158]'
document.getElementById('arr559').innerHTML ='$subval3[159]'
document.getElementById('arr560').innerHTML ='$subval3[160]'
document.getElementById('arr561').innerHTML ='$subval3[161]'
document.getElementById('arr562').innerHTML ='$subval3[162]'
document.getElementById('arr563').innerHTML ='$subval3[163]'
document.getElementById('arr564').innerHTML ='$subval3[164]'
document.getElementById('arr565').innerHTML ='$subval3[165]'
document.getElementById('arr566').innerHTML ='$subval3[166]'
document.getElementById('arr567').innerHTML ='$subval3[167]'
document.getElementById('arr568').innerHTML ='$subval3[168]'
document.getElementById('arr569').innerHTML ='$subval3[169]'
document.getElementById('arr570').innerHTML ='$subval3[170]'
document.getElementById('arr571').innerHTML ='$subval3[171]'
document.getElementById('arr572').innerHTML ='$subval3[172]'
document.getElementById('arr573').innerHTML ='$subval3[173]'
document.getElementById('arr574').innerHTML ='$subval3[174]'
document.getElementById('arr575').innerHTML ='$subval3[175]'
document.getElementById('arr576').innerHTML ='$subval3[176]'
     </script>";

/////Third year printing ends here////




//////Fourth Year progress started here  /////



$sqlval4= "SELECT * FROM fouryear WHERE id='$studentid'";
$resultval4 = mysqli_query($conn, $sqlval4);

if (mysqli_num_rows($resultval4) > 0){
    // output data of each row
   
     while($arrayval4=mysqli_fetch_row($resultval4)) 
    {
        for($i=0;$i<=176;$i++)
        {
          $subval4[]=$arrayval4[$i];
            
            
        }
         
    }
}
else {
//    echo "Error: " . $sqlval . "<br>" . mysqli_error($conn);
}
echo "<script type=\"text/javascript\">
document.getElementById('arr601').innerHTML ='$subval4[1]'
document.getElementById('arr602').innerHTML ='$subval4[2]'
document.getElementById('arr603').innerHTML ='$subval4[3]'
document.getElementById('arr604').innerHTML ='$subval4[4]'
document.getElementById('arr605').innerHTML ='$subval4[5]'
document.getElementById('arr606').innerHTML ='$subval4[6]'
document.getElementById('arr607').innerHTML ='$subval4[7]'
document.getElementById('arr608').innerHTML ='$subval4[8]'
document.getElementById('arr609').innerHTML ='$subval4[9]'
document.getElementById('arr610').innerHTML ='$subval4[10]'
document.getElementById('arr611').innerHTML ='$subval4[11]'
document.getElementById('arr612').innerHTML ='$subval4[12]'
document.getElementById('arr613').innerHTML ='$subval4[13]'
document.getElementById('arr614').innerHTML ='$subval4[14]'
document.getElementById('arr615').innerHTML ='$subval4[15]'
document.getElementById('arr616').innerHTML ='$subval4[16]'
document.getElementById('arr617').innerHTML ='$subval4[17]'
document.getElementById('arr618').innerHTML ='$subval4[18]'
document.getElementById('arr619').innerHTML ='$subval4[19]'
document.getElementById('arr620').innerHTML ='$subval4[20]'
document.getElementById('arr621').innerHTML ='$subval4[21]'
document.getElementById('arr622').innerHTML ='$subval4[22]'
document.getElementById('arr623').innerHTML ='$subval4[23]'
document.getElementById('arr624').innerHTML ='$subval4[24]'
document.getElementById('arr625').innerHTML ='$subval4[25]'
document.getElementById('arr626').innerHTML ='$subval4[26]'
document.getElementById('arr627').innerHTML ='$subval4[27]'
document.getElementById('arr628').innerHTML ='$subval4[28]'
document.getElementById('arr629').innerHTML ='$subval4[29]'
document.getElementById('arr630').innerHTML ='$subval4[30]'
document.getElementById('arr631').innerHTML ='$subval4[31]'
document.getElementById('arr632').innerHTML ='$subval4[32]'
document.getElementById('arr633').innerHTML ='$subval4[33]'
document.getElementById('arr634').innerHTML ='$subval4[34]'
document.getElementById('arr635').innerHTML ='$subval4[35]'
document.getElementById('arr636').innerHTML ='$subval4[36]'
document.getElementById('arr637').innerHTML ='$subval4[37]'
document.getElementById('arr638').innerHTML ='$subval4[38]'
document.getElementById('arr639').innerHTML ='$subval4[39]'
document.getElementById('arr640').innerHTML ='$subval4[40]'
document.getElementById('arr641').innerHTML ='$subval4[41]'
document.getElementById('arr642').innerHTML ='$subval4[42]'
document.getElementById('arr643').innerHTML ='$subval4[43]'
document.getElementById('arr644').innerHTML ='$subval4[44]'
document.getElementById('arr646').innerHTML ='$subval4[46]'
document.getElementById('arr648').innerHTML ='$subval4[48]'
document.getElementById('arr649').innerHTML ='$subval4[49]'
document.getElementById('arr651').innerHTML ='$subval4[51]'
document.getElementById('arr653').innerHTML ='$subval4[53]'
document.getElementById('arr654').innerHTML ='$subval4[54]'
document.getElementById('arr655').innerHTML ='$subval4[55]'
document.getElementById('arr657').innerHTML ='$subval4[57]'
document.getElementById('arr659').innerHTML ='$subval4[59]'
document.getElementById('arr660').innerHTML ='$subval4[60]'
document.getElementById('arr662').innerHTML ='$subval4[62]'
document.getElementById('arr664').innerHTML ='$subval4[64]'
document.getElementById('arr665').innerHTML ='$subval4[65]'
document.getElementById('arr666').innerHTML ='$subval4[66]'
document.getElementById('arr667').innerHTML ='$subval4[67]'
document.getElementById('arr668').innerHTML ='$subval4[68]'
document.getElementById('arr669').innerHTML ='$subval4[69]'
document.getElementById('arr670').innerHTML ='$subval4[70]'
document.getElementById('arr671').innerHTML ='$subval4[71]'
document.getElementById('arr672').innerHTML ='$subval4[72]'
document.getElementById('arr673').innerHTML ='$subval4[73]'
document.getElementById('arr674').innerHTML ='$subval4[74]'
document.getElementById('arr675').innerHTML ='$subval4[75]'
document.getElementById('arr676').innerHTML ='$subval4[76]'
document.getElementById('arr677').innerHTML ='$subval4[77]'
document.getElementById('arr678').innerHTML ='$subval4[78]'
document.getElementById('arr679').innerHTML ='$subval4[79]'
document.getElementById('arr680').innerHTML ='$subval4[80]'
document.getElementById('arr681').innerHTML ='$subval4[81]'
document.getElementById('arr682').innerHTML ='$subval4[82]'
document.getElementById('arr683').innerHTML ='$subval4[83]'
document.getElementById('arr684').innerHTML ='$subval4[84]'
document.getElementById('arr685').innerHTML ='$subval4[85]'
document.getElementById('arr686').innerHTML ='$subval4[86]'
document.getElementById('arr687').innerHTML ='$subval4[87]'
document.getElementById('arr688').innerHTML ='$subval4[88]'
document.getElementById('arr689').innerHTML ='$subval4[89]'
document.getElementById('arr690').innerHTML ='$subval4[90]'
document.getElementById('arr691').innerHTML ='$subval4[91]'
document.getElementById('arr692').innerHTML ='$subval4[92]'
document.getElementById('arr693').innerHTML ='$subval4[93]'
document.getElementById('arr694').innerHTML ='$subval4[94]'
document.getElementById('arr695').innerHTML ='$subval4[95]'
document.getElementById('arr696').innerHTML ='$subval4[96]'
document.getElementById('arr697').innerHTML ='$subval4[97]'
document.getElementById('arr698').innerHTML ='$subval4[98]'
document.getElementById('arr699').innerHTML ='$subval4[99]'
document.getElementById('arr700').innerHTML ='$subval4[100]'
document.getElementById('arr701').innerHTML ='$subval4[101]'
document.getElementById('arr702').innerHTML ='$subval4[102]'
document.getElementById('arr703').innerHTML ='$subval4[103]'
document.getElementById('arr704').innerHTML ='$subval4[104]'
document.getElementById('arr705').innerHTML ='$subval4[105]'
document.getElementById('arr706').innerHTML ='$subval4[106]'
document.getElementById('arr707').innerHTML ='$subval4[107]'
document.getElementById('arr708').innerHTML ='$subval4[108]'
document.getElementById('arr709').innerHTML ='$subval4[109]'
document.getElementById('arr710').innerHTML ='$subval4[110]'
document.getElementById('arr712').innerHTML ='$subval4[112]'
document.getElementById('arr714').innerHTML ='$subval4[114]'
document.getElementById('arr715').innerHTML ='$subval4[115]'
document.getElementById('arr717').innerHTML ='$subval4[117]'
document.getElementById('arr719').innerHTML ='$subval4[119]'
document.getElementById('arr720').innerHTML ='$subval4[120]'
document.getElementById('arr721').innerHTML ='$subval4[121]'
document.getElementById('arr723').innerHTML ='$subval4[123]'
document.getElementById('arr725').innerHTML ='$subval4[125]'
document.getElementById('arr726').innerHTML ='$subval4[126]'
document.getElementById('arr728').innerHTML ='$subval4[128]'
document.getElementById('arr730').innerHTML ='$subval4[130]'
document.getElementById('arr731').innerHTML ='$subval4[131]'
document.getElementById('arr732').innerHTML ='$subval4[132]'
document.getElementById('arr733').innerHTML ='$subval4[133]'
document.getElementById('arr734').innerHTML ='$subval4[134]'
document.getElementById('arr735').innerHTML ='$subval4[135]'
document.getElementById('arr736').innerHTML ='$subval4[136]'
document.getElementById('arr737').innerHTML ='$subval4[137]'
document.getElementById('arr738').innerHTML ='$subval4[138]'
document.getElementById('arr739').innerHTML ='$subval4[139]'
document.getElementById('arr740').innerHTML ='$subval4[140]'
document.getElementById('arr741').innerHTML ='$subval4[141]'
document.getElementById('arr742').innerHTML ='$subval4[142]'
document.getElementById('arr743').innerHTML ='$subval4[143]'
document.getElementById('arr744').innerHTML ='$subval4[144]'
document.getElementById('arr745').innerHTML ='$subval4[145]'
document.getElementById('arr746').innerHTML ='$subval4[146]'
document.getElementById('arr747').innerHTML ='$subval4[147]'
document.getElementById('arr748').innerHTML ='$subval4[148]'
document.getElementById('arr749').innerHTML ='$subval4[149]'
document.getElementById('arr750').innerHTML ='$subval4[150]'
document.getElementById('arr751').innerHTML ='$subval4[151]'
document.getElementById('arr752').innerHTML ='$subval4[152]'
document.getElementById('arr753').innerHTML ='$subval4[153]'
document.getElementById('arr754').innerHTML ='$subval4[154]'
document.getElementById('arr755').innerHTML ='$subval4[155]'
document.getElementById('arr756').innerHTML ='$subval4[156]'
document.getElementById('arr757').innerHTML ='$subval4[157]'
document.getElementById('arr758').innerHTML ='$subval4[158]'
document.getElementById('arr759').innerHTML ='$subval4[159]'
document.getElementById('arr760').innerHTML ='$subval4[160]'
document.getElementById('arr761').innerHTML ='$subval4[161]'
document.getElementById('arr762').innerHTML ='$subval4[162]'
document.getElementById('arr763').innerHTML ='$subval4[163]'
document.getElementById('arr764').innerHTML ='$subval4[164]'
document.getElementById('arr765').innerHTML ='$subval4[165]'
document.getElementById('arr766').innerHTML ='$subval4[166]'
document.getElementById('arr767').innerHTML ='$subval4[167]'
document.getElementById('arr768').innerHTML ='$subval4[168]'
document.getElementById('arr769').innerHTML ='$subval4[169]'
document.getElementById('arr770').innerHTML ='$subval4[170]'
document.getElementById('arr771').innerHTML ='$subval4[171]'
document.getElementById('arr772').innerHTML ='$subval4[172]'
document.getElementById('arr773').innerHTML ='$subval4[173]'
document.getElementById('arr774').innerHTML ='$subval4[174]'
document.getElementById('arr775').innerHTML ='$subval4[175]'
document.getElementById('arr776').innerHTML ='$subval4[176]'
 </script>";
?>